version: '3'

tasks:
  bump:
    desc: 'Bump the module version in the .psd1 file. Usage: "task bump -- show" or "task bump -- [patch|minor|major]".'
    preconditions:
      - sh: 'pwsh -c "if (Get-Command bump) { exit 0 } else { exit 1 }"'
        msg: "The 'bump' command is not available. Please install the required tools to use this command."
    cmds:
      - |
        {{if eq .CLI_ARGS "show"}}
          pwsh -c "bump show -f lib/Q3Rcon.psd1 -p \"ModuleVersion\s*=\s'(\d+\.\d+\.\d+)'\""
        {{else}}
          pwsh -c "bump {{.CLI_ARGS}} -w -f lib/Q3Rcon.psd1 -p \"ModuleVersion\s*=\s'(\d+\.\d+\.\d+)'\""
        {{end}}
